services:
  db:
    image: postgres
    network_mode: host
    env_file:
      - .env
  api:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./api
        target: /api
